name: DwR
favicon: null
layout_spectrum: 0.6404122426174581
typography_spectrum: 0.501821955665946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8586108258459717
  lightness: 0.279278471134603
  saturation: 0.2735538680572063
  rhythmicContrast: 0.5530703966505826
purpose: []
