typography_spectrum: 0.75635
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8586108258459717
  lightness: 0.279278471134603
  saturation: 0.2735538680572063
  rhythmicContrast: 0.5530703966505826
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74648
analytics:
  google: null
  facebook: null
  twitter: null
name: DwR
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Driving with Robots
purpose: []
